"""
Auto Complaint Generator — Generates FIR-ready cybercrime complaint letters
Uses Groq LLM to draft professional complaint text, outputs as downloadable text.
"""

import os
import json
from datetime import datetime
from typing import Dict, List, Any

def generate_complaint_text(session_data: Dict[str, Any]) -> str:
    """Generate a formal cybercrime complaint letter from session intelligence"""
    
    session = session_data.get('session', {})
    messages = session_data.get('messages', [])
    intelligence = session_data.get('intelligence', [])
    
    session_id = session.get('session_id', 'UNKNOWN')
    started_at = session.get('started_at', datetime.now().isoformat())
    persona = session.get('persona', 'N/A')
    stage = session.get('final_stage', 'N/A')
    confidence = session.get('scam_confidence', 0)
    
    # Categorize intelligence
    banks = [i for i in intelligence if i.get('intel_type') == 'bank_account']
    upis = [i for i in intelligence if i.get('intel_type') == 'upi_id']
    phones = [i for i in intelligence if i.get('intel_type') == 'phone']
    links = [i for i in intelligence if i.get('intel_type') == 'link']
    
    # Build conversation transcript
    transcript_lines = []
    for msg in messages:
        sender = "SCAMMER" if msg.get('sender') == 'scammer' else "VICTIM (AI AGENT)"
        transcript_lines.append(f"  [{sender}]: {msg.get('message_text', '')}")
    transcript = "\n".join(transcript_lines) if transcript_lines else "  No transcript available."
    
    # Build intel summary
    intel_lines = []
    if banks:
        intel_lines.append("  BANK ACCOUNTS:")
        for b in banks:
            intel_lines.append(f"    - Account: {b['value']} (Confidence: {b.get('confidence', 0):.0%})")
    if upis:
        intel_lines.append("  UPI IDS:")
        for u in upis:
            intel_lines.append(f"    - UPI: {u['value']} (Confidence: {u.get('confidence', 0):.0%})")
    if phones:
        intel_lines.append("  PHONE NUMBERS:")
        for p in phones:
            intel_lines.append(f"    - Phone: {p['value']} (Confidence: {p.get('confidence', 0):.0%})")
    if links:
        intel_lines.append("  PHISHING LINKS:")
        for l in links:
            intel_lines.append(f"    - URL: {l['value']} (Confidence: {l.get('confidence', 0):.0%})")
    
    intel_summary = "\n".join(intel_lines) if intel_lines else "  No intelligence extracted."
    
    total_intel = len(banks) + len(upis) + len(phones) + len(links)
    
    complaint = f"""
════════════════════════════════════════════════════════════════
                    CYBERCRIME COMPLAINT REPORT
              Auto-Generated by Agentic Honey-Pot System
════════════════════════════════════════════════════════════════

DATE OF REPORT:     {datetime.now().strftime('%d %B %Y, %I:%M %p IST')}
REFERENCE NUMBER:   HP-{session_id[:8].upper()}
SYSTEM VERSION:     Agentic Honey-Pot v3.0

────────────────────────────────────────────────────────────────
SECTION 1: INCIDENT SUMMARY
────────────────────────────────────────────────────────────────

This complaint is auto-generated based on a cyber fraud interaction
captured by the Agentic Honey-Pot AI system. The system engaged
with a suspected scammer and extracted the following intelligence.

  Incident Date:      {started_at}
  Detection Method:   AI-Powered Honeypot Analysis
  Scam Confidence:    {confidence:.0%}
  Conversation Stage: {stage}
  Total Messages:     {len(messages)}
  Total Intel Items:  {total_intel}

────────────────────────────────────────────────────────────────
SECTION 2: EXTRACTED INTELLIGENCE
────────────────────────────────────────────────────────────────

{intel_summary}

────────────────────────────────────────────────────────────────
SECTION 3: CONVERSATION TRANSCRIPT
────────────────────────────────────────────────────────────────

{transcript}

────────────────────────────────────────────────────────────────
SECTION 4: RECOMMENDED ACTION
────────────────────────────────────────────────────────────────

  Based on the extracted intelligence, the following actions are
  recommended:

  1. FREEZE the bank accounts listed above through coordination
     with the respective banks
  2. TRACE the phone numbers through telecom service providers
  3. BLOCK the phishing URLs through CERT-In
  4. INVESTIGATE the UPI IDs through the National Payments
     Corporation of India (NPCI)

────────────────────────────────────────────────────────────────
SECTION 5: SYSTEM CERTIFICATION
────────────────────────────────────────────────────────────────

  This report was automatically generated by the Agentic Honey-Pot
  AI System v3.0. All intelligence items were extracted using
  pattern matching and AI analysis with confidence scores assigned
  to each data point.

  System Operator: Agentic Honey-Pot Team
  Report Generated: {datetime.now().strftime('%d/%m/%Y %H:%M:%S IST')}

════════════════════════════════════════════════════════════════
              END OF COMPLAINT REPORT — HP-{session_id[:8].upper()}
════════════════════════════════════════════════════════════════
"""
    return complaint.strip()
